name: "Testing tutorials"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_tutorials:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[test]
        python3 -m pip install .
        # Dependencies for tutorials
        python3 -m pip install jupyter pandas ezyrb opencv-python ffmpeg-python

    - uses: actions/cache@v2
      id: cache-segtrackv2
      with:
        path: ./tutorials/tutorial12/SegTrackv2
        key: SegTrackv2-key

    # This is needed for tutorial12
    - name: Download SegTrackv2
      if: steps.cache-segtrackv2.outputs.cache-hit != 'true'
      run: |
        curl https://web.engr.oregonstate.edu/~lif/SegTrack2/SegTrackv2.zip --output SegTrackv2.zip
        unzip -qq SegTrackv2.zip
        mv SegTrackv2 tutorials/tutorial12

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
        
    - name: Test tutorials
      run: |
        cd tutorials/
        for dir in $(ls -d tutorial*/); do
          if [[ $dir != tutorial5* ]]
            then
            python3 -m jupyter nbconvert --to notebook --execute ${dir}*.ipynb
          fi
        done