name: "Update tutorials"

on:
  push:
    branches:
      - master
    paths:
      - 'tutorials/**/*.ipynb'

jobs:
  test_deploy:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[test]
        python3 -m pip install jupyter

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        
    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Convert tutorials
      run: |
        for file in ${{ steps.files.outputs.all }}; do
          if [[ $file == *.ipynb ]]; then
            filename=$(basename $file)

            pyfilename=$(echo ${filename%?????})py
            jupyter nbconvert --execute $file --to python --output $pyfilename
            git add $(dirname $file)/${pyfilename}

            htmlfilename=$(echo ${filename%?????})html
            jupyter nbconvert --execute $file --to html --output $htmlfilename
            git add $(dirname $file)/${htmlfilename}
          fi
        done
      
    - name: Push changes
      run: |
        git commit -m "update tutorials ($GITHUB_SHA)"
        git push
        
